import { Metadata } from 'next'
import { ReactNode } from 'react'
import { Header } from './components/header/header'
import { Footer } from './components/footer/footer'

export const metadat: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
